%macro ISR_WITHOUT_ERROR_CODE 1
	global isr%1
	
	isr%1:
		cli
		push byte 0
		push byte %1
		jmp isr_common_handler

%endmacro

%macro ISR_WITH_ERROR_CODE 1
	global isr%1
	
	isr%1: 
		cli
		push byte %1
		jmp isr_common_handler
		
%endmacro

ISR_WITHOUT_ERROR_CODE 0
ISR_WITHOUT_ERROR_CODE 1
ISR_WITHOUT_ERROR_CODE 2
ISR_WITHOUT_ERROR_CODE 3
ISR_WITHOUT_ERROR_CODE 4
ISR_WITHOUT_ERROR_CODE 5
ISR_WITHOUT_ERROR_CODE 6
ISR_WITHOUT_ERROR_CODE 7
ISR_WITHOUT_ERROR_CODE 9
ISR_WITHOUT_ERROR_CODE 15
ISR_WITHOUT_ERROR_CODE 16
ISR_WITHOUT_ERROR_CODE 18
ISR_WITHOUT_ERROR_CODE 19
ISR_WITHOUT_ERROR_CODE 20
ISR_WITHOUT_ERROR_CODE 21
ISR_WITHOUT_ERROR_CODE 22
ISR_WITHOUT_ERROR_CODE 23
ISR_WITHOUT_ERROR_CODE 24
ISR_WITHOUT_ERROR_CODE 25
ISR_WITHOUT_ERROR_CODE 26
ISR_WITHOUT_ERROR_CODE 27
ISR_WITHOUT_ERROR_CODE 28
ISR_WITHOUT_ERROR_CODE 29
ISR_WITHOUT_ERROR_CODE 30
ISR_WITHOUT_ERROR_CODE 31

ISR_WITH_ERROR_CODE 8
ISR_WITH_ERROR_CODE 10
ISR_WITH_ERROR_CODE 11
ISR_WITH_ERROR_CODE 12
ISR_WITH_ERROR_CODE 13
ISR_WITH_ERROR_CODE 14
ISR_WITH_ERROR_CODE 17

global isr_common_handler
extern isr_handler

isr_common_handler:
	pushad
	
	mov ax, ds
	push eax
	
	mov ax, 0x10
	mov ds, ax
	mov es, ax
	mov fs, ax
	mov gs, ax
	
	call isr_handler
	
	pop eax
	mov ds, ax
	mov es, ax
	mov fs, ax
	mov gs, ax
	
	popad
	add esp, 8
	sti
	
	iret
	